trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  dependsOn: job3
  steps:
  - script: echo Hello, guys this is job1 script!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job2
  dependsOn: job4
  steps:
  - script: echo Hello, guys this is job2 script!
    displayName: 'Run a one-line script'

- job: job3
  dependsOn: 
  - job2
  steps:
  - script: echo Hello, guys this is job3 script!
    displayName: 'Run a one-line script'

- job: job4
  steps:
  - script: echo Hello, guys this is job4 script!
    displayName: 'Run a one-line script'
