trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: First_job
      steps:
        - bash: echo first job in Build stage
    - job: Second_job
      steps:
        - bash: echo second job in Build stage

  - stage: DevDeploy
    jobs:
      - job: Dev_Job
        steps:
        - bash: echo first job in Dev-Deploy stage

  - stage: ProdDeploy
    jobs:
      - job: Prod_Job
        steps:
          - bash: echo first job in Prod-Deploy stage

