trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: First_job
      steps:
        - bash: echo first job in Build stage
        - bash: echo new $(PipelineLevelVariables) is created
    - job: Second_job
      steps:
        - bash: echo second job in Build stage

  - stage: DevDeploy
    variables:
      env: Dev
    dependsOn: Build
    jobs:
      - job: Dev_Job
        steps:
        - bash: echo first job in Dev-Deploy stage

  - stage: QaDeploy
    variables:
      env: Qa
    dependsOn: Build
    jobs:
      - job: Qa_Job
        steps:
        - bash: echo first job in Qa-Deploy stage

  - stage: ProdDeploy
    variables:
      env: Prod
    dependsOn: 
    - DevDeploy
    - QaDeploy
    jobs:
      - job: Prod_Job
        steps:
          - bash: echo first job in Prod-Deploy stage

