trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: First_job
      steps:
        - bash: echo first job in Build stage
        - bash: echo $(PipelineLevelVariable)
        - bash: echo $(Build.BuildNumber)
        - bash: echo $(Build.BuildId)
        - bash: echo $(Build.SourceBranchName)
        - bash: echo $(Build.SourceDirectory)
        - bash: echo $(Build.ArtifactStagingDirectory)
        - bash: echo $(System.DefaultWorkingDirectory)
        - bash: ls -R $(System.DefaultWorkingDirectory)
  #   - job: Second_job
  #     steps:
  #       - bash: echo second job in Build stage

  # - stage: DevDeploy
  #   dependsOn: Build
  #   jobs:
  #     - job: Dev_Job
  #       steps:
  #       - bash: echo first job in Dev-Deploy stage

  # - stage: QaDeploy
  #   dependsOn: Build
  #   jobs:
  #     - job: Qa_Job
  #       steps:
  #       - bash: echo first job in Qa-Deploy stage

  # - stage: ProdDeploy
  #   dependsOn: 
  #   - DevDeploy
  #   - QaDeploy
  #   jobs:
  #     - job: Prod_Job
  #       steps:
  #         - bash: echo first job in Prod-Deploy stage
