trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: First-job
      steps:
        - bash: echo first job in Build stage
    - job: Second-job
      steps:
        - bash: echo second job in Build stage

  - stage: Dev-Deploy
    jobs:
      - job: Dev-Job
        steps:
        - bash: echo first job in Dev-Deploy stage

  - stage: Prod-Deploy
    jobs:
      - job: Prod-Job
        steps:
          - bash: echo first job in Prod-Deploy stage

