trigger:
- master

strategy:
  matrix:
   linux:
     operatingSystem: 'ubuntu-latest'
   mac:
     operatingSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Hello, $(operatingSystem) world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy in $(operatingSystem).
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
